# Generated by Django 2.2.1 on 2019-06-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrApp', '0005_remove_atendimento_queixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='receita',
            field=models.TextField(null=True),
        ),
    ]
