# Generated by Django 2.2.1 on 2019-06-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrApp', '0006_atendimento_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atestado',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='solicitacao_exame_imagem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='solicitacao_exame_lab',
            field=models.TextField(null=True),
        ),
    ]
