# Generated by Django 2.2.1 on 2019-06-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrApp', '0007_auto_20190620_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='receita',
        ),
    ]
