# Generated by Django 2.2.1 on 2019-06-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrApp', '0010_auto_20190620_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receituario',
        ),
    ]
