# Generated by Django 2.2.1 on 2019-06-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrApp', '0011_delete_receituario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receituario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_droga', models.CharField(default='', max_length=200)),
                ('apresentacao_droga', models.CharField(default='', max_length=200)),
                ('quantidade_droga', models.CharField(default='', max_length=200)),
                ('forma_uso_droga', models.CharField(default='', max_length=200)),
                ('duracao_uso_droga', models.CharField(default='', max_length=200)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrApp.Atendimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrApp.Paciente')),
            ],
        ),
    ]
