# Generated by Django 2.2.1 on 2019-06-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrApp', '0012_receituario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
